{% set name = "amplpy" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61237df756aabdc10fe86c45dc9ac252af69e6dbc5dd8ba9d378c735de78d44e

build:
  number: 0
  skip: true  # [python_impl == "pypy"]
#  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - future >=0.15.0
    - pip
    - python
  run:
    - future >=0.15.0
    - python

test:
  imports:
    - amplpy

about:
  home: http://ampl.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python API for AMPL
  doc_url: https://amplpy.readthedocs.io
  dev_url: https://github.com/ampl/amplpy

extra:
  recipe-maintainers:
    - fdabrandao
