{% set name = "amplpy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e6368bd1de08ef7748cfd5efee6883d772637c58b8562feef300c300b85b654

build:
  number: 0
  skip: True  # [python_impl == "pypy"]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - future >=0.15.0
    - pip
    - python
  run:
    - future >=0.15.0
    - python

test:
  imports:
    - amplpy

about:
  home: http://ampl.com/
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: Python API for AMPL
  doc_url: https://amplpy.readthedocs.io
  dev_url: https://github.com/ampl/amplpy

extra:
  recipe-maintainers:
    - fdabrandao
