travis:
  secure:
    BINSTAR_TOKEN: ZceDT5fstomdiU2pkk2QBZG1FmMx8Uvtsnw2Wfcz+anzUPCr3W+WuKcUrrfTzuWta1GclPDx1oOjF3FR5s4BRPcZmGmqxKswezEKCwYOveaFmT0jwTKCoz4F8EFhLW49iiDZ3E8jqHNsH4U9+EakQMMX4jA+ncq6F9mrok/fAzMAwEv5szZw6JfHdmTJDfIsAJ+e6YPg+22qi7xQHhUNFQCx+hVKQXDqOtYxHUJlhKrPBlp8PB8iqw94jb38ZPLsItNqkCOzORPiOR9T2Ew8sfW7blXkBy6chUoAK2+Mnk+kevsrdpuuQcwVIJbneZP/0eElh0VpWlv7ckf/23d9wRHnv/iHX3f1ro1GGavLq8NEqGm6nFfYVHXzajS4SkRY9q0gLL7Ug+4C6qPSxUnrNIOYBH2h3MhqV5oUrPuenpJFtPhX+A/DlF0n/3po1tLP752Vc2226vffdvYHthluFHD8n1JIUyFKG9JI3yscEMtkTo9HBhEmPVXZR+C/+vd6kRv6rubq0fxt/pyDaoI3HBhpqgvfAMznA1Q1Rnq1JLuzwQuLGMZCgrV17DPi4munYTRKPCMKSXeuOZzifLQRfmAlzpuNu5ghtsbpgI/trw/poTU5iX0Xm0+xJXyWtCGnTM9mtEqP1MSs1u2+nZ373pybq72fRQrkP8Q1F3uexmc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
